<?php

/**
 * @file
 * merci_template functions
 */

/**
 * Implementation of hook_menu().
 */
function merci_template_menu() {

  $items = array();

  $items['merci/templates'] = array(
    'title' => 'Start a Reservation from a Template',
    'page callback' => 'merci_template_list',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  // Administration settings.
  $items['admin/settings/merci/template'] = array(
    'title' => 'Template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('merci_template_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'description' => t('Configure template settings for MERCI.'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
  );

  return $items;
}

/**
 * Builds the MERCI admininstration settings form.
 */
function merci_template_admin_settings() {
  $form = array();

  $form['merci_template_hide_details'] = array(
    '#type' => 'checkbox',
    '#title' => t('Hide Details of Reservation When Using a Template'),
    '#default_value' => variable_get('merci_template_hide_details', 0),
  );

  return system_settings_form($form);
}


function merci_template_list() {
  $result = db_query("SELECT title, draft_id, node_type FROM {drafts} WHERE title IS NOT NULL");

  while ($merci_template = db_fetch_object($result)) {

    $output .= l(t('Reserve ' . $merci_template->title), 'node/add/' . str_replace("_", "-", $merci_template->node_type), array('query' => array('draft_id' => $merci_template->draft_id), 'attributes' => array('class' => 'button'))) . '<br />';

  }

  if (!$output) {
    $output = t('There are no Templates.');
  }

  return $output;
}

/**
 * Implementation of hook_form_alter().
 */
function merci_template_form_merci_reservation_node_form_alter(&$form, $form_state) {
  //dsm($form);
  drupal_add_js(drupal_get_path('module', 'merci_template') . '/merci_template.js');


  if (isset($_GET['draft_id']) && is_numeric($_GET['draft_id']) && variable_get('merci_template_hide_details', 0)) {
    $draft_id = $_GET['draft_id'];

    drupal_add_js("$(document).ready(function() { $('#merci-choices').toggle(); $('#edit-merci-more').toggle(); });", 'inline');

    $result = db_fetch_object(db_query("SELECT * FROM {drafts} WHERE draft_id = %d", $_GET['draft_id']));

    $form['draft_name'] = array(
      '#type' => 'markup',
      '#title' => t('Room'),
      '#value' => '<div class="message status"><div style="padding: 10px">Reserving ' . $result->title . ' (<a id="show-merci-choices">show details</a>)</div></div>',
      '#weight' => -4,
    );

  }

  $form['update_draft_id'] = array(
    '#type' => 'hidden',
    '#value' => $draft_id,
  );
}
// merci_template_form_alter

function merci_template_draft($op, $draft_id, $draft_data = array(), &$form) {
  foreach ($draft_data as $key => $item) {
    if (preg_match("/^choice\((\d{1,5})\)\(item\)$/", $key, $matches)) {
      $delta = $matches[1];
      if ($delta > 2) {
        $form['choice_wrapper']['choice'][$delta] = _merci_choice_form($node, $form_state, $delta);
      }
    }
  }
}


