<?php
/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function ultimosganadores_help($path, $arg) 
{
  $output = '';  //declare your output variable
  switch ($path) {
    case 'admin/help#ultimosganadores':
      $output = '<p>' . t('Displays links to nodes created on this date') . '</p>';
		break;
  }
  return $output;
} // function ultimosganadores_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the ultimosganadores module
*/
function ultimosganadores_perm() 
{
  return array('access ultimosganadores content');
} // function ultimosganadores_perm()



function ultimosganadores_block($op='list', $delta=0) 
{
  // set up the block  
  $block = array();

  if ($op == 'list') {
    // Generate listing of blocks from this module, for the admin/block page

    $block[0]['info'] = t('UltimosGanadores');
  } 
  else if ($op == 'view') {

    // Generate our block content

    // content variable that will be returned for display
    $block_content = '';

    // Get today's date
    $today = getdate();

    // calculate midnight one week ago
    $start_time = mktime(0, 0, 0,$today['mon'],
                               ($today['mday'] - 7), $today['year']);

    // we want items that occur only on the day in question, so 
    //calculate 1 day
    $end_time = $start_time + 86400;
    // 60 * 60 * 24 = 86400 seconds in a day

    $query = 'SELECT u.uid as idusuario, n.nid as idoferta, c.field_coste_puntos_value as puntos, ca.fecha as fecha,
			 n.title as nombreoferta, u.name as nombreusuario FROM {node} n, {users} u,{content_type_oferta} c,
			 {canjeo} ca WHERE n.nid=ca.nid and u.uid=ca.uid and c.nid=n.nid ORDER BY ca.fecha DESC LIMIT 5';
	
	 
    $query_result =  db_query($query);
    while ($links = db_fetch_object($query_result)) {
	  //$block_content .= l ($links->nombreusuario, 'user/'.$links->idusuario) . '<br />' ;
	  $dia=substr($links->fecha,8,2);
	  $mes=substr($links->fecha,5,2);
	  $ano=substr($links->fecha,0,4);
	  $block_content .= l ($links->nombreusuario, 'user/' . $links->idusuario).' ' . $dia .'/' .$mes . '/' . $ano .' '
					 . l ($links->nombreoferta, 'node/' . $links->idoferta) . '<br />' ;
    }

    // Fill in the subject of our block which is the same whether or not
    // the block has any real content
    $block['subject'] = '&Uacute;ltimos ganadores';

    // check to see if there was any content before returning
    //  the block view
    if ($block_content == '') {   
       // no content from a week ago
       $block['content'] = 'No hay ganadores';
    }
    else {
      // set up the block
      $block['content'] = $block_content;
    }
  }
  return $block;
}  // end ultimosganadores_block